const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.Spawn
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{spr_ground_01: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{spr_player: 0},
	{Teclado: 0},
	{plataforma_1: 0},
	{plataforma_2: 0},
	{plataforma_3: 0},
	{Senóide: 0},
	{plataforma_4: 0},
	{ball: 0},
	{arrow: 0},
	{bg1: 0},
	{bg2: 0},
	{bg3: 0},
	{bg4: 0},
	{death: 0},
	{Áudio: 0},
	{grass_01: 0},
	{grass_02: 0},
	{arrow2: 0},
	{p: 0},
	{black_fi: 0},
	{black_fo: 0}
];

self.InstanceType = {
	spr_ground_01: class extends self.ISpriteInstance {},
	spr_player: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	plataforma_1: class extends self.ISpriteInstance {},
	plataforma_2: class extends self.ISpriteInstance {},
	plataforma_3: class extends self.ISpriteInstance {},
	plataforma_4: class extends self.ISpriteInstance {},
	ball: class extends self.ISpriteInstance {},
	arrow: class extends self.ISpriteInstance {},
	bg1: class extends self.ISpriteInstance {},
	bg2: class extends self.ISpriteInstance {},
	bg3: class extends self.ISpriteInstance {},
	bg4: class extends self.ISpriteInstance {},
	death: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	grass_01: class extends self.ISpriteInstance {},
	grass_02: class extends self.ISpriteInstance {},
	arrow2: class extends self.ISpriteInstance {},
	p: class extends self.ISpriteInstance {},
	black_fi: class extends self.ISpriteInstance {},
	black_fo: class extends self.ISpriteInstance {}
}